# Generated by Django 5.1.6 on 2025-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_is_used_sharedlink_is_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedlink",
            name="removed_by_recipient",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the recipient has removed this shared file from their view",
            ),
        ),
    ]
