# Generated by Django 5.1.6 on 2025-03-14 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_sharedlink_removed_by_recipient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="trash_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filemetadata",
            name="trashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="file_path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
